# Generated by Django 4.1.7 on 2023-06-01 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0004_alter_caja_fecha_alta_alter_caja_fecha_hora_alta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='fecha_alta',
            field=models.CharField(default='31/05/2023', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='caja',
            name='fecha_hora_alta',
            field=models.CharField(default='31/05/2023 22:37:19 hs', max_length=500, null=True),
        ),
    ]
