# Generated by Django 4.1.7 on 2023-06-12 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('caja', '0005_alter_caja_fecha_alta_alter_caja_fecha_hora_alta'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='id_usuario_cierre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='caja',
            name='fecha_alta',
            field=models.CharField(default='12/06/2023', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='caja',
            name='fecha_hora_alta',
            field=models.CharField(default='12/06/2023 18:38:26 hs', max_length=500, null=True),
        ),
    ]
