# Generated by Django 4.1.7 on 2023-06-18 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoVacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_vacuna', models.CharField(blank=True, max_length=500, null=True)),
                ('periodo_aplicacion', models.CharField(blank=True, max_length=500, null=True)),
                ('multi_aplicaciones', models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], default='N', max_length=2, null=True)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
            ],
            options={
                'verbose_name': 'Vacunas',
                'verbose_name_plural': 'Vacunas',
                'permissions': (('add_tipovacuna', 'Agregar Vacuna'), ('change_tipovacuna', 'Editar Vacuna'), ('delete_tipovacuna', 'Eliminar Vacuna'), ('view_tipovacuna', 'Listar Vacunas')),
                'default_permissions': (),
            },
        ),
    ]
