# Generated by Django 4.1.7 on 2023-06-18 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timbrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_timbrado', models.CharField(blank=True, max_length=500, null=True)),
                ('fecha_inicio_timbrado', models.CharField(blank=True, max_length=500, null=True)),
                ('fecha_fin_timbrado', models.CharField(blank=True, max_length=500, null=True)),
                ('vencido', models.CharField(blank=True, default='N', max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VacunasAplicadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_aplicadas', models.FloatField(blank=True, default=0, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('id_producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
            ],
        ),
        migrations.CreateModel(
            name='ServicioVendido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_vendida_total', models.FloatField(blank=True, default=0, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('id_producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoVendidoMes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('cantidad_vendida_total', models.FloatField(blank=True, default=0, null=True)),
                ('id_producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoVendido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_vendida_total', models.FloatField(blank=True, default=0, null=True)),
                ('id_producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
            ],
        ),
    ]
