# Generated by Django 4.1.7 on 2023-05-22 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_alter_producto_options_alter_tipoproducto_options_and_more'),
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_factura', models.CharField(max_length=500, null=True)),
                ('nro_timbrado', models.CharField(max_length=500, null=True)),
                ('fecha_alta', models.CharField(default='21/05/2023', max_length=500, null=True)),
                ('fecha_emision_factura', models.CharField(max_length=500, null=True)),
                ('fecha_emision', models.CharField(max_length=500, null=True)),
                ('fecha_vencimiento', models.CharField(max_length=500, null=True)),
                ('tipo_factura', models.BooleanField(default=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CANCELADO', 'Cancelado'), ('FINALIZADO', 'Finalizado')], default=('PENDIENTE', 'Pendiente'), max_length=500)),
                ('total_iva', models.IntegerField(default=0)),
                ('total', models.FloatField(default=0)),
                ('factura_cargada_producto', models.CharField(blank=True, default='N', max_length=2, null=True)),
                ('factura_cargada_pedido', models.CharField(blank=True, default='N', max_length=2, null=True)),
                ('pedidod_to_factura', models.CharField(blank=True, default='N', max_length=2, null=True)),
                ('facturado', models.CharField(blank=True, default='N', max_length=2, null=True)),
                ('factura_caja', models.CharField(blank=True, default='N', max_length=2, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.CharField(blank=True, default='S', max_length=2, null=True)),
            ],
            options={
                'verbose_name': 'Factura Compra',
                'verbose_name_plural': 'Facturas Compras',
                'permissions': (('add_facturacompra', 'Agregar Factura Compra'), ('change_facturacompra', 'Editar Factura Compra'), ('delete_facturacompra', 'Eliminar Factura Compra'), ('view_facturacompra', 'Listar Factura Compra')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_pago', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Plural',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_pedido', models.CharField(blank=True, default='-', max_length=500, null=True)),
                ('fecha_alta', models.CharField(default='21/05/2023 23:04:05 hs', editable=False, max_length=200)),
                ('pedido_cargado', models.CharField(blank=True, default='N', max_length=2, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.CharField(blank=True, default='S', max_length=2, null=True)),
                ('id_producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='productos.producto')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'permissions': (('add_pedido', 'Agregar Pedido normal'), ('change_pedido', 'Editar Pedido normal'), ('delete_pedido', 'Eliminar Pedido normal'), ('view_pedido', 'Listar Pedido normal')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='PedidoCabecera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_alta', models.CharField(default='21/05/2023', editable=False, max_length=200)),
                ('pedido_cargado', models.CharField(blank=True, default='N', max_length=2, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.CharField(blank=True, default='S', max_length=2, null=True)),
            ],
            options={
                'verbose_name': 'Pedido Cabecera',
                'verbose_name_plural': 'Pedido Cabeceras',
                'permissions': (('add_pedidocabecera', 'Agregar Pedido'), ('change_pedidocabecera', 'Editar Pedido'), ('delete_pedidocabecera', 'Eliminar Pedido'), ('view_pedidocabecera', 'Listar Pedido')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='PedidoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=800)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('id_pedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.pedido')),
                ('id_pedido_cabecera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.pedidocabecera')),
                ('id_producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='productos.producto')),
            ],
            options={
                'verbose_name': 'Pedido Detalle',
                'verbose_name_plural': 'Pedido Detalle',
                'permissions': (('add_pedidodetalle', 'Agregar Pedido'), ('change_pedidodetalle', 'Editar Pedido'), ('delete_pedidodetalle', 'Eliminar Pedido'), ('view_pedidodetalle', 'Listar Pedido')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FacturaDet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_compra', models.CharField(blank=True, max_length=800, null=True)),
                ('detalle_cargado_reporte', models.CharField(blank=True, default='N', max_length=2, null=True)),
                ('detalle_cargado_mes', models.CharField(blank=True, default='N', max_length=2, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=800)),
                ('id_factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.facturacompra')),
                ('id_pedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.pedido')),
                ('id_producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='productos.producto')),
            ],
        ),
        migrations.AddField(
            model_name='facturacompra',
            name='id_pedido_cabecera',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.pedidocabecera'),
        ),
        migrations.AddField(
            model_name='facturacompra',
            name='id_proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compras.proveedor'),
        ),
    ]
