# Generated by Django 4.0.4 on 2023-03-19 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoproducto',
            name='fecha_alta',
            field=models.CharField(default='19/03/2023 19:56:07 hs', editable=False, max_length=200),
        ),
    ]
