# Generated by Django 4.0.4 on 2023-04-30 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('depositos', '0001_initial'),
        ('productos', '0003_alter_tipoproducto_fecha_alta'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fecha_compra',
            field=models.CharField(default='29/04/2023', editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_movimiento',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='id_deposito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='depositos.deposito'),
        ),
        migrations.AddField(
            model_name='producto',
            name='id_servicio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='producto_vencido',
            field=models.CharField(blank=True, default='N', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='servicio_o_producto',
            field=models.CharField(blank=True, default='P', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_movido',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tipoproducto',
            name='fecha_alta',
            field=models.CharField(default='29/04/2023 22:26:57 hs', editable=False, max_length=200),
        ),
        migrations.CreateModel(
            name='ProductoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_stock', models.IntegerField(help_text='Ingrese stock')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.CharField(blank=True, default='S', max_length=2, null=True)),
                ('id_deposito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='depositos.deposito')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_viejo', models.IntegerField(blank=True, default=0, null=True)),
                ('stock_fisico', models.IntegerField(blank=True, default=0, null=True)),
                ('diferencia', models.IntegerField(blank=True, default=0, null=True)),
                ('fecha_alta', models.CharField(default='29/04/2023 22:26:57 hs', max_length=500, null=True)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoProductoPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_alta', models.CharField(default='29/04/2023', max_length=500, null=True)),
                ('precio_compra', models.CharField(blank=True, max_length=500, null=True)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
            ],
        ),
    ]
