# Generated by Django 4.1.7 on 2023-05-22 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_producto_fecha_compra_producto_fecha_movimiento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'default_permissions': (), 'permissions': (('add_producto', 'Agregar Producto'), ('change_producto', 'Editar Producto'), ('delete_producto', 'Eliminar Producto'), ('view_producto', 'Listar Productos')), 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='tipoproducto',
            options={'default_permissions': (), 'permissions': (('add_tipoproducto', 'Agregar Tipo Producto'), ('change_tipoproducto', 'Editar Tipo Producto'), ('delete_tipoproducto', 'Eliminar Tipo Producto'), ('view_tipoproducto', 'Listar Tipo Productos')), 'verbose_name': 'Tipo Producto', 'verbose_name_plural': 'Tipo Productos'},
        ),
        migrations.AlterField(
            model_name='historicoproductoprecio',
            name='fecha_alta',
            field=models.CharField(default='21/05/2023', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='fecha_alta',
            field=models.CharField(default='21/05/2023 23:04:05 hs', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_compra',
            field=models.CharField(default='21/05/2023', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='tipoproducto',
            name='fecha_alta',
            field=models.CharField(default='21/05/2023 23:04:05 hs', editable=False, max_length=200),
        ),
    ]
