# Generated by Django 4.1.7 on 2023-06-01 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_alter_producto_options_alter_tipoproducto_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicoproductoprecio',
            name='fecha_alta',
            field=models.CharField(default='31/05/2023', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='fecha_alta',
            field=models.CharField(default='31/05/2023 22:37:19 hs', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_compra',
            field=models.CharField(default='31/05/2023', editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='tipoproducto',
            name='fecha_alta',
            field=models.CharField(default='31/05/2023 22:37:19 hs', editable=False, max_length=200),
        ),
    ]
