# Generated by Django 4.1.7 on 2023-06-12 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion_inicial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='confiempresa',
            name='nro_caja',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='confiempresa',
            name='nro_factura',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='confiempresa',
            name='nro_sucursal',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
