# Generated by Django 4.0.4 on 2023-03-25 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
        ('mascotas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_mascota', models.CharField(help_text='Ingrese nombre de la mascota', max_length=200)),
                ('tatuaje', models.CharField(blank=True, default='-', help_text='Ingrese el tatuaje', max_length=200, null=True)),
                ('sexo', models.CharField(choices=[('MAC', 'Macho'), ('HEB', 'Hembra')], default='-', help_text='Seleccione el sexo', max_length=15)),
                ('edad', models.CharField(blank=True, default='-', max_length=200, null=True)),
                ('imagen', models.ImageField(blank=True, help_text='Ingrese una foto', null=True, upload_to='mascotas/fotos')),
                ('peso', models.CharField(help_text='Ingrese el peso de la mascota', max_length=200)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('masc_reservado', models.CharField(blank=True, default='S', max_length=200, null=True)),
                ('fecha_reservada', models.CharField(blank=True, max_length=200, null=True)),
                ('hora_reserva', models.CharField(blank=True, max_length=200, null=True)),
                ('color_pelaje', models.CharField(blank=True, default='-', help_text='Ingrese el color de la mascota', max_length=200, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
                ('id_raza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascotas.raza')),
            ],
            options={
                'verbose_name': 'Mascota',
                'verbose_name_plural': 'Mascotas',
                'permissions': (('add_mascota', 'Agregar Mascota'), ('change_mascota', 'Editar Mascota'), ('delete_mascota', 'Eliminar Mascota'), ('view_mascota', 'Listar Mascotas')),
                'default_permissions': (),
            },
        ),
    ]
