# Generated by Django 4.0.4 on 2023-04-30 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_vacuna', '0001_initial'),
        ('mascotas', '0002_mascota'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_create', models.DateTimeField(auto_now=True)),
                ('id_mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascotas.mascota')),
            ],
            options={
                'verbose_name': 'Ficha Medica',
                'verbose_name_plural': 'Fichas Medicas',
            },
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proxima_vacuna', models.CharField(blank=True, max_length=500, null=True)),
                ('fecha_aplicacion', models.CharField(blank=True, max_length=500, null=True)),
                ('fecha_proxima_aplicacion', models.CharField(blank=True, max_length=500, null=True)),
                ('id_ficha_medica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascotas.fichamedica')),
                ('id_vacuna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tipo_vacuna.tipovacuna')),
            ],
            options={
                'verbose_name': 'Ficha Medica',
                'verbose_name_plural': 'Fichas Medicas',
            },
        ),
        migrations.CreateModel(
            name='HistoricoFichaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proxima_vacunacion', models.CharField(blank=True, default='-', max_length=500, null=True)),
                ('diagnostico', models.CharField(blank=True, default='-', max_length=500, null=True)),
                ('tratamiento', models.CharField(blank=True, default='-', max_length=500, null=True)),
                ('proximo_tratamiento', models.CharField(blank=True, default='-', max_length=500, null=True)),
                ('medicamento', models.CharField(blank=True, default='-', max_length=500, null=True)),
                ('fecha_aplicacion', models.CharField(blank=True, max_length=500, null=True)),
                ('fecha_proxima_aplicacion', models.CharField(blank=True, max_length=500, null=True)),
                ('antiparasitario', models.CharField(blank=True, default='-', max_length=500, null=True)),
                ('proximo_antiparasitario', models.CharField(blank=True, default='-', max_length=500, null=True)),
                ('peso', models.CharField(blank=True, default='-', max_length=200, null=True)),
                ('fecha_alta', models.CharField(blank=True, max_length=500, null=True)),
                ('historico_cargado_reporte', models.CharField(blank=True, default='N', max_length=2, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('id_ficha_medica', models.IntegerField(blank=True, null=True)),
                ('id_mascota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mascotas.mascota')),
                ('vacuna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tipo_vacuna.tipovacuna')),
            ],
            options={
                'verbose_name': 'Historico Ficha Medicas',
                'verbose_name_plural': 'Historicos Fichas Medicas',
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico', models.CharField(blank=True, default='-', max_length=500, null=True)),
                ('tratamiento', models.CharField(blank=True, default='-', max_length=500, null=True)),
                ('proximo_tratamiento', models.CharField(blank=True, default='-', max_length=500, null=True)),
                ('medicamento', models.CharField(blank=True, default='-', max_length=500, null=True)),
                ('id_ficha_medica', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mascotas.fichamedica')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
            },
        ),
        migrations.CreateModel(
            name='Antiparasitario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antiparasitario', models.CharField(blank=True, default='-', max_length=500, null=True)),
                ('proximo_antiparasitario', models.CharField(blank=True, default='-', max_length=500, null=True)),
                ('id_ficha_medica', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mascotas.fichamedica')),
            ],
            options={
                'verbose_name': 'Antiparasitario',
                'verbose_name_plural': 'Antiparasitarios',
            },
        ),
    ]
