# Generated by Django 4.0.4 on 2023-04-30 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_alter_cabeceraventa_fecha_alta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabeceraventa',
            name='fecha_alta',
            field=models.CharField(default='29/04/2023', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cabeceraventa',
            name='fecha_emision',
            field=models.CharField(default='29/04/2023 22:26:57 hs', max_length=500, null=True),
        ),
    ]
